spring:
  h2:
    console:
      enabled: true
      path: /h2-consoles
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    generate-ddl: false

security:
  jwt:
    key: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E
    token:
      expire-length: 3600000
